from spaceone.inventory.info.common_info import *
from spaceone.inventory.info.region_info import *
from spaceone.inventory.info.job_info import *
from spaceone.inventory.info.job_task_info import *
from spaceone.inventory.info.cloud_service_type_info import *
from spaceone.inventory.info.cloud_service_info import *
from spaceone.inventory.info.cloud_service_query_set_info import *
from spaceone.inventory.info.cloud_service_stats_info import *
from spaceone.inventory.info.cloud_service_report_info import *
from spaceone.inventory.info.collector_info import *
from spaceone.inventory.info.change_history_info import *
from spaceone.inventory.info.note_info import *
from spaceone.inventory.info.collector_rule_info import *
