PROTO = {
    'spaceone.inventory.api.v1.region': ['Region'],
    # 'zone': ['Zone'],
    # 'pool': ['Pool'],
    # 'network_type': ['NetworkType'],
    # 'network_policy': ['NetworkPolicy'],
    # 'network': ['Network'],
    # 'subnet': ['Subnet'],
    # 'ip_address': ['IPAddress'],
    'spaceone.inventory.api.v1.server': ['Server'],
    'spaceone.inventory.api.v1.collector': ['Collector'],
    'spaceone.inventory.api.v1.job': ['Job'],
    'spaceone.inventory.api.v1.job_task': ['JobTask'],
    'spaceone.inventory.api.v1.cloud_service_type': ['CloudServiceType'],
    'spaceone.inventory.api.v1.cloud_service': ['CloudService'],
    'spaceone.inventory.api.v1.resource_group': ['ResourceGroup'],
}
