---
metric_id: metric-managed-iam-service-account
name: Service Account Count
metric_type: GAUGE
resource_type: identity.ServiceAccount
query_options:
  group_by:
    - key: workspace_id
      name: Workspace ID
    - key: provider
      name: Provider
      default: true
    - key: state
      name: State
    - key: is_managed
      name: AutoSync
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-managed-iam-summary
version: '1.0'