---
metric_id: metric-managed-iam-user
name: User Count
metric_type: GAUGE
resource_type: identity.User
query_options:
  group_by:
    - key: state
      name: State
      default: true
    - key: role_type
      name: Role Type
    - key: auth_type
      name: Auth Type
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-managed-iam-summary
version: '1.0'