---
metric_id: metric-managed-total-count
name: Total Count
metric_type: GAUGE
resource_type: inventory.CloudService
query_options:
  group_by:
    - key: provider
      name: Provider
      reference:
        resource_type: identity.Provider
        reference_key: provider
      default: true
    - key: cloud_service_group
      name: Cloud Service Group
      default: true
    - key: cloud_service_type
      name: Cloud Service Type
      default: true
    - key: region_code
      name: Region
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Cloud Account ID
  fields:
    value:
      operator: count
  filter:
    - key: ref_cloud_service_type.labels
      value: CSPM
      operator: not
    - key: ref_cloud_service_type.is_primary
      value: True
      operator: eq
unit: Count
namespace_id: ns-managed-asset-summary
version: '1.0'